### ISSUE TITLE
How can this sample improve its accuracy?

### ISSUE THREAD

**Issue by XavierNJ** [ppplinday/tensorflow-vgg16-train-and-test#2]
First, thank you for sharing your codes.
And after i used your codes, i found that the accuracy is very low, what else can i do to improve it?

**Comment by zz234807** [comment]
https://blog.csdn.net/u014432647/article/details/75276718
人家只是个练手项目 @XavierNJ

**Comment by ppplinday** [comment]
Hi, XavierNJ, if you want to update accuracy, you can see my another project which is also a good project for studying.[https://github.com/ppplinday/TFrecord-Lenet-Vgg19-tensorflow](https://github.com/ppplinday/TFrecord-Lenet-Vgg19-tensorflow)
Hope this can help u, enjoy!
